CREATE TABLE shipplotter
  mmsi    INT,
  timestamp INT,
  status    INT,
  type    INT,
  lat     DECIMAL,
  lon     DECrrMAL,
  speed   DECIMAL,
  course    DECIMAL,
  heading   INT,
  draft   DECIMAL,
  length    INT,
  beam    INT,
  name    CHAR(20),
  callsign, CHAR(7),
  dest    CHAR(20),
  etaDate   CHAR(5),
  etaTime   CHAR(5),
  x1      CHAR(1),
  x2      INT,
  x3      INT,
  x4      INT,
  x5      INT,
  PRIMARY KEY (mmsi, timestamp)
  
CREATE TABLE shipplotter
  mmsi    INTEGER,
  timestamp INTEGER,
  status    INTEGER,
  type    INTEGER,
  lat     DECIMAL,
  lon     DECIMAL,
  speed   DECIMAL,
  course    DECIMAL,
  heading   INTEGER,
  draft   DECIMAL,
  length    INTEGER,
  beam    INTEGER,
  name    CHAR(20),
  callsign, CHAR(7),
  dest    CHAR(20),
  etaDate   CHAR(5),
  etaTime   CHAR(5),
  x1      CHAR(1),
  x2      INTEGER,
  x3      INTEGER,
  x4      INTEGER,
  x5      INTEGER,
  PRIMARY KEY (mmsi, timestamp)
  
